### ISSUE TITLE
Function doesn't accept nullable personNumber

### ISSUE THREAD

**Issue by ChameleonTartu** [MikAoJk/norwegian-social-security-number-validator#2]
It would be great if this function would accept `personNumber` as a `String?`

```
fun validateSocialSecurityAndDNumber(personNumber: String): Boolean =
    validateSocialSecurityNumberMod11(personNumber) && validatePersonAndPersonDNumberRange(personNumber)
```

Can you possibly add it? If you need any help with this, I would be happy to assist (not sure about code standards and practices you are following).

**Comment by MikAoJk** [comment]
yes, i will add it now

**Comment by MikAoJk** [comment]
Feature added in version 1.0.3
